enhance: Readability improvements (#16)
* enhance: use kebab case for inputs

* enhance: rename target-type input from pr to pull_request

* fix: remove cruft

* fix: use correct notice log syntax

diff --git a/comment/action.yml b/comment/action.yml
--- a/comment/action.yml
+++ b/comment/action.yml
@@ -8,10 +8,10 @@ inputs:
     description: The behavior to use when posting cost estimate comments. Must be one of 'update' | 'delete_and_new' | 'hide_and_new' | 'new'.
     required: false
     default: update
-  targetType:
-    description: Which objects should be commented on, either `pr` (for pull requests) or `commit`.
+  target-type:
+    description: Which objects should be commented on, either `pull_request` or `commit`.
     required: false
-  GITHUB_TOKEN:
+  github-token:
     description: 'Default to {{ github.token }}. This is the default GitHub token available to actions and is used to post comments.'
     default: '${{ github.token }}'
     required: false
@@ -20,20 +20,31 @@ runs:
   steps:
     - name: Run infracost output
       shell: bash
+      id: run-infracost-output
       run: |
+        # validate inputs
+        if [ "${{ inputs.target-type }}" = "commit" ]; then
+          echo '::set-output name=target-type::commit'
+        elif [ "${{ inputs.target-type }}" != "pull_request" ]; then
+          echo '::set-output name=target-type::pr'
+        else
+          echo "::error::Invalid target-type '${{ inputs.target-type }}'.  Must be commit or pull_request."
+          exit 1
+        fi
+
         # handle multiple paths
         if jq . >/dev/null 2>&1 <<< '${{ inputs.path }}'; then
           paths=$(jq -r 'if type == "array" then map("--path " + .) | join(" ") else . end' <<< '${{ inputs.path }}')
         else
           paths="--path ${{ inputs.path }}"
         fi
-        echo "::info::Using paths: $paths"
+        echo "::notice::Using paths: $paths"
 
         export INFRACOST_CI_POST_CONDITION=${{ inputs.behavior }}
 
         infracost output $paths --format github-comment --show-skipped --out-file comment.md
 
-        if [ "${{ inputs.targetType }}" != "commit" ]; then
+        if [ "${{ inputs.target-type }}" != "commit" ]; then
           if [ "${{ inputs.behavior }}" = "update" ]; then
             printf "\nThis comment will be updated when the cost estimate changes.\n\n" >> comment.md
           elif [ "${{ inputs.behavior }}" = "delete_and_new" ]; then
@@ -49,7 +60,7 @@ runs:
       with:
         bodyFile: comment.md
         behavior: ${{ inputs.behavior }}
-        targetType: ${{ inputs.targetType }}
-        GITHUB_TOKEN: ${{ github.token }}
+        targetType: ${{ steps.run-infracost-output.outputs.target-type }}
+        GITHUB_TOKEN: ${{ inputs.github-token }}
 
 
